### ISSUE TITLE
Can you install packages?

### ISSUE THREAD

**Issue by AndrewSav** [fireflycons/tips-for-CKA-CKAD-CKS#3]
Thank you for publishing this. I'm sure many people including me, find it most helpful.

You wrote:

>You may not install additional software from package repos or other locations except when directed by an exam question, and only from the links or instructions it gives you, e.g. you can use apt during a cluster upgrade question, but you cannot use it to install some other utility you think would aid you.

The [handbook](https://docs.linuxfoundation.org/tc-docs/certification/certification-resources-allowed#certified-kubernetes-administrator-cka-and-certified-kubernetes-application-developer-ckad) says:

> During the exam, candidates may: <...> use Packages that are part of the distribution (may also be installed by Candidate if not available by default)

I wanted to clarify, are you referring to the same thing as the handbook, or to something else?

**Comment by fireflycons** [comment]
Thank you for raising this @AndrewSav .

Guidance may have changed since I created this page. I will raise a ticket with Linux Foundation to clarify exactly what they mean by this, especially "part of the distribution". I take this to mean that you are not allowed to add additional apt repositories other than those required to download Kubernetes components.

I will update the page when I receive their response (3-5 working days).

**Comment by fireflycons** [comment]
This has now been updated.
